name: Rust CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Install Rust toolchain (stable) via the rust-lang setup action
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly

      - name: Build all crates
        run: cargo build --workspace --all-targets --verbose

      - name: Test all crates
        run: cargo test --workspace --all-targets --verbose
